import type { BlockDefinition } from '../types/registry'
import { componentRegistry } from './componentRegistry'
import {
  BlockButton,
  BlockCheckbox,
  BlockColumns,
  BlockContainer,
  BlockDivider,
  BlockFooter,
  BlockForm,
  BlockHeading,
  BlockImage,
  BlockInput,
  BlockLabel,
  BlockNavbar,
  BlockOption,
  BlockPage,
  BlockRadio,
  BlockSection,
  BlockSelect,
  BlockSpan,
  BlockText,
  BlockTextArea,
  BlockTextField,
} from './blocks'

const builtins: BlockDefinition[] = [
  {
    type: 'Page',
    label: 'Page',
    category: 'layout',
    component: BlockPage,
    schema: [
      { key: 'title', type: 'text', label: 'Page title (data only)' },
      { key: 'slug', type: 'text', label: 'Slug (data only)' },
    ],
    defaultProps: { title: 'Home', slug: '/' },
    defaultStyles: {
      minHeight: '100%',
      display: 'flex',
      flexDirection: 'column',
    },
    acceptsChildren: true,
  },
  {
    type: 'Section',
    label: 'Section',
    category: 'layout',
    component: BlockSection,
    schema: [],
    defaultProps: {},
    defaultStyles: {
      padding: 'var(--spacing-xl) var(--spacing-lg)',
      backgroundColor: 'var(--color-background)',
    },
    acceptsChildren: true,
  },
  {
    type: 'Container',
    label: 'Container',
    category: 'layout',
    component: BlockContainer,
    schema: [],
    defaultProps: {},
    defaultStyles: { maxWidth: '960px', margin: '0 auto', width: '100%' },
    acceptsChildren: true,
  },
  {
    type: 'Columns',
    label: 'Columns (2)',
    category: 'layout',
    component: BlockColumns,
    schema: [],
    defaultProps: {},
    defaultStyles: {
      display: 'grid',
      gridTemplateColumns: '1fr 1fr',
      gap: 'var(--spacing-lg)',
    },
    acceptsChildren: true,
  },
  {
    type: 'Divider',
    label: 'Divider',
    category: 'layout',
    component: BlockDivider,
    schema: [],
    defaultProps: {},
    defaultStyles: {
      border: 'none',
      borderTop: '1px solid var(--color-border)',
      margin: 'var(--spacing-md) 0',
    },
    acceptsChildren: false,
  },
  {
    type: 'Navbar',
    label: 'Navbar',
    category: 'navigation',
    component: BlockNavbar,
    schema: [],
    defaultProps: {},
    defaultStyles: {
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 'var(--spacing-lg)',
      flexWrap: 'wrap',
      padding: 'var(--spacing-md) var(--spacing-lg)',
      backgroundColor: 'var(--color-surface)',
      borderBottom: '1px solid var(--color-border)',
    },
    acceptsChildren: true,
  },
  {
    type: 'Footer',
    label: 'Footer',
    category: 'navigation',
    component: BlockFooter,
    schema: [],
    defaultProps: {},
    defaultStyles: {
      padding: 'var(--spacing-lg)',
      backgroundColor: 'var(--color-surface)',
      borderTop: '1px solid var(--color-border)',
      textAlign: 'center',
      color: 'var(--color-text-muted)',
      fontSize: '14px',
    },
    acceptsChildren: true,
  },
  {
    type: 'Span',
    label: 'Span (text)',
    category: 'typography',
    component: BlockSpan,
    schema: [{ key: 'text', type: 'text', label: 'Text payload' }],
    defaultProps: { text: 'Text' },
    defaultStyles: {},
    acceptsChildren: false,
  },
  {
    type: 'Heading',
    label: 'Heading',
    category: 'typography',
    component: BlockHeading,
    schema: [],
    defaultProps: {},
    defaultStyles: {
      fontFamily: 'var(--font-heading)',
      color: 'var(--color-text)',
      margin: '0 0 var(--spacing-sm)',
    },
    acceptsChildren: true,
  },
  {
    type: 'Text',
    label: 'Paragraph',
    category: 'typography',
    component: BlockText,
    schema: [],
    defaultProps: {},
    defaultStyles: {
      fontFamily: 'var(--font-body)',
      fontSize: 'var(--font-size-base)',
      color: 'var(--color-text-muted)',
      lineHeight: '1.6',
      margin: '0 0 var(--spacing-md)',
    },
    acceptsChildren: true,
  },
  {
    type: 'Image',
    label: 'Image',
    category: 'media',
    component: BlockImage,
    schema: [
      { key: 'src', type: 'text', label: 'Image URL (legacy — prefer Meta)', placeholder: 'https://…' },
      { key: 'alt', type: 'text', label: 'Alt (legacy — prefer Meta)' },
    ],
    defaultProps: {},
    defaultStyles: {
      width: '100%',
      borderRadius: 'var(--border-radius-md)',
      objectFit: 'cover',
      display: 'block',
    },
    acceptsChildren: false,
  },
  {
    type: 'Button',
    label: 'Button',
    category: 'interactive',
    component: BlockButton,
    schema: [
      { key: 'label', type: 'text', label: 'Label (legacy if no children)' },
      { key: 'href', type: 'text', label: 'URL (legacy — prefer Meta)' },
    ],
    defaultProps: {},
    defaultStyles: {
      display: 'inline-block',
      padding: '12px 24px',
      backgroundColor: 'var(--color-primary)',
      color: '#fff',
      borderRadius: 'var(--border-radius-md)',
      fontWeight: '600',
      textDecoration: 'none',
      border: 'none',
      cursor: 'pointer',
      fontFamily: 'var(--font-body)',
    },
    acceptsChildren: true,
  },
  {
    type: 'Input',
    label: 'Input',
    category: 'forms',
    component: BlockInput,
    schema: [
      { key: 'type', type: 'text', label: 'Input type', placeholder: 'text, email, password…' },
      { key: 'placeholder', type: 'text', label: 'Placeholder' },
      { key: 'value', type: 'text', label: 'Default value' },
    ],
    defaultProps: { type: 'text', placeholder: 'Type here…', value: '' },
    defaultStyles: { padding: '10px 12px', border: '1px solid var(--color-border)', borderRadius: '8px' },
    acceptsChildren: false,
  },
  {
    type: 'TextField',
    label: 'Text Field',
    category: 'forms',
    component: BlockTextField,
    schema: [
      { key: 'placeholder', type: 'text', label: 'Placeholder' },
      { key: 'value', type: 'text', label: 'Default value' },
    ],
    defaultProps: { placeholder: 'Enter text', value: '' },
    defaultStyles: { padding: '10px 12px', border: '1px solid var(--color-border)', borderRadius: '8px' },
    acceptsChildren: false,
  },
  {
    type: 'TextArea',
    label: 'Text Area',
    category: 'forms',
    component: BlockTextArea,
    schema: [
      { key: 'placeholder', type: 'text', label: 'Placeholder' },
      { key: 'value', type: 'textarea', label: 'Default value' },
      { key: 'rows', type: 'number', label: 'Rows', min: 2, max: 20 },
    ],
    defaultProps: { placeholder: 'Write your message…', value: '', rows: 4 },
    defaultStyles: { padding: '10px 12px', border: '1px solid var(--color-border)', borderRadius: '8px' },
    acceptsChildren: false,
  },
  {
    type: 'Select',
    label: 'Select',
    category: 'forms',
    component: BlockSelect,
    schema: [],
    defaultProps: {},
    defaultStyles: { padding: '10px 12px', border: '1px solid var(--color-border)', borderRadius: '8px' },
    acceptsChildren: true,
  },
  {
    type: 'Option',
    label: 'Option',
    category: 'forms',
    component: BlockOption,
    schema: [
      { key: 'value', type: 'text', label: 'Value' },
      { key: 'label', type: 'text', label: 'Label' },
    ],
    defaultProps: { value: 'option-1', label: 'Option 1' },
    defaultStyles: {},
    acceptsChildren: false,
  },
  {
    type: 'Checkbox',
    label: 'Checkbox',
    category: 'forms',
    component: BlockCheckbox,
    schema: [
      { key: 'label', type: 'text', label: 'Label' },
      { key: 'checked', type: 'text', label: 'Checked (true/false)' },
    ],
    defaultProps: { label: 'Accept terms', checked: false },
    defaultStyles: { display: 'inline-flex', alignItems: 'center', gap: '8px' },
    acceptsChildren: true,
  },
  {
    type: 'Radio',
    label: 'Radio',
    category: 'forms',
    component: BlockRadio,
    schema: [
      { key: 'name', type: 'text', label: 'Group name' },
      { key: 'label', type: 'text', label: 'Label' },
      { key: 'checked', type: 'text', label: 'Checked (true/false)' },
    ],
    defaultProps: { name: 'group', label: 'Option', checked: false },
    defaultStyles: { display: 'inline-flex', alignItems: 'center', gap: '8px' },
    acceptsChildren: true,
  },
  {
    type: 'Label',
    label: 'Label',
    category: 'forms',
    component: BlockLabel,
    schema: [],
    defaultProps: {},
    defaultStyles: {},
    acceptsChildren: true,
  },
  {
    type: 'Form',
    label: 'Form',
    category: 'forms',
    component: BlockForm,
    schema: [],
    defaultProps: {},
    defaultStyles: { display: 'flex', flexDirection: 'column', gap: '12px' },
    acceptsChildren: true,
  },
]

export function registerBuiltinBlocks() {
  for (const def of builtins) {
    componentRegistry.register(def)
  }
}
